services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env.dev
    environment:
      APP_ENV: dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  celery:
    env_file:
      - ./.env.dev
    environment:
      APP_ENV: dev
    volumes:
      - .:/app
