# Generated by Django 5.2.7 on 2026-04-05 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0018_alter_deposituploadlog_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(db_index=True, help_text='YYYYMM 형식 (예: 202603)', max_length=6, verbose_name='월도')),
                ('bizmoon_total', models.CharField(blank=True, default='', max_length=100, verbose_name='부문총괄')),
                ('bizmoon', models.CharField(blank=True, default='', max_length=50, verbose_name='부문')),
                ('total', models.CharField(blank=True, default='', max_length=50, verbose_name='총괄')),
                ('part', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='부서')),
                ('branch', models.CharField(blank=True, default='', max_length=100, verbose_name='영업가족')),
                ('branch_code', models.CharField(blank=True, default='', max_length=50, verbose_name='영업가족코드')),
                ('affiliation', models.CharField(blank=True, default='', max_length=300, verbose_name='소속')),
                ('regist_type', models.CharField(blank=True, default='', max_length=50, verbose_name='등록구분')),
                ('emp_name', models.CharField(blank=True, default='', max_length=100, verbose_name='사원명')),
                ('work_status', models.CharField(blank=True, default='', max_length=50, verbose_name='재직(설계사)')),
                ('enter_date', models.DateField(blank=True, null=True, verbose_name='입사일')),
                ('emp_id', models.CharField(db_index=True, max_length=30, verbose_name='사번')),
                ('final_payment', models.BigIntegerField(default=0, verbose_name='최종지급액')),
                ('approval', models.CharField(blank=True, default='', max_length=10, verbose_name='결재')),
                ('pay_flag', models.CharField(blank=True, default='', max_length=10, verbose_name='지급')),
                ('surety_bond_total', models.BigIntegerField(default=0, verbose_name='보증채권합계')),
                ('surety_bond_detail', models.CharField(blank=True, default='', max_length=200, verbose_name='보증/채권')),
                ('collect_action', models.CharField(blank=True, default='', max_length=200, verbose_name='환수조치')),
                ('status', models.CharField(blank=True, default='', max_length=100, verbose_name='상태')),
                ('action_detail', models.CharField(blank=True, default='', max_length=500, verbose_name='조치상세')),
                ('car', models.BigIntegerField(default=0, verbose_name='자동차')),
                ('general', models.BigIntegerField(default=0, verbose_name='일반')),
                ('ns_init', models.BigIntegerField(default=0, verbose_name='손보초회')),
                ('ns_cont', models.BigIntegerField(default=0, verbose_name='손보계속')),
                ('ns_total', models.BigIntegerField(default=0, verbose_name='손보합계')),
                ('ls_init', models.BigIntegerField(default=0, verbose_name='생보초회')),
                ('ls_cont', models.BigIntegerField(default=0, verbose_name='생보계속')),
                ('ls_total', models.BigIntegerField(default=0, verbose_name='생보합계')),
                ('etc_pay', models.BigIntegerField(default=0, verbose_name='기타지급')),
                ('etc_deduct', models.BigIntegerField(default=0, verbose_name='기타공제')),
                ('prepay', models.BigIntegerField(default=0, verbose_name='선지급')),
                ('first_pay', models.BigIntegerField(default=0, verbose_name='1차지급')),
                ('tax', models.BigIntegerField(default=0, verbose_name='세금')),
                ('actual_pay', models.BigIntegerField(default=0, verbose_name='실지급액')),
                ('self_settle', models.BigIntegerField(default=0, verbose_name='자체정산')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='업로드일시')),
            ],
            options={
                'verbose_name': '환수관리 레코드',
                'verbose_name_plural': '환수관리 레코드',
                'db_table': 'collect_record',
                'ordering': ['ym', 'part', 'emp_id'],
                'indexes': [models.Index(fields=['ym', 'part'], name='idx_collect_record_ym_part'), models.Index(fields=['ym', 'bizmoon'], name='idx_collect_record_ym_bizmoon')],
                'constraints': [models.UniqueConstraint(fields=('emp_id', 'ym'), name='uq_collect_record_empid_ym')],
            },
        ),
        migrations.CreateModel(
            name='CollectFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(db_index=True, help_text='CollectRecord.emp_id와 동일 형식. FK 없이 독립 저장.', max_length=30, verbose_name='대상자 사번')),
                ('content', models.TextField(verbose_name='피드백 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collect_feedbacks_written', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '환수 피드백',
                'verbose_name_plural': '환수 피드백',
                'db_table': 'collect_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['emp_id', '-created_at'], name='idx_collect_feedback_empid_dt')],
            },
        ),
        migrations.CreateModel(
            name='CollectUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(db_index=True, help_text='YYYYMM 형식', max_length=6, verbose_name='업로드 월도')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='업로드일시')),
                ('row_count', models.IntegerField(default=0, verbose_name='처리 행 수')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='원본 파일명')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collect_upload_logs', to=settings.AUTH_USER_MODEL, verbose_name='업로드 사용자')),
            ],
            options={
                'verbose_name': '환수관리 업로드 이력',
                'verbose_name_plural': '환수관리 업로드 이력',
                'db_table': 'collect_upload_log',
                'ordering': ['-uploaded_at'],
                'constraints': [models.UniqueConstraint(fields=('ym',), name='uq_collect_uploadlog_ym')],
            },
        ),
    ]
