# Generated by Django 5.2.7 on 2026-04-24 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0019_add_collect_record_feedback_uploadlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectDropdownFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(db_index=True, max_length=30, verbose_name='대상자 사번')),
                ('ym', models.CharField(db_index=True, max_length=6, verbose_name='월도(YYYYMM)')),
                ('feedback_type', models.CharField(choices=[('branch', '영업가족 피드백'), ('hq', '본사 피드백')], max_length=10, verbose_name='피드백 구분')),
                ('value', models.CharField(blank=True, default='', max_length=30, verbose_name='피드백 값')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collect_dropdown_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '환수관리 드랍다운 피드백',
                'verbose_name_plural': '환수관리 드랍다운 피드백',
                'db_table': 'collect_dropdown_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['emp_id', 'ym', 'feedback_type'], name='idx_collect_df_empid_ym_type')],
            },
        ),
    ]
