# Generated by Django 5.2.7 on 2026-04-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0020_add_collect_dropdown_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectfeedback',
            name='date_input',
            field=models.DateField(blank=True, help_text='피드백 작성 기준일 (자동 입력일과 별개)', null=True, verbose_name='입력일'),
        ),
        migrations.AddField(
            model_name='collectfeedback',
            name='department',
            field=models.CharField(blank=True, choices=[('채권추심부', '채권추심부'), ('담당부서', '담당부서'), ('영업지점', '영업지점')], default='', max_length=20, verbose_name='담당부서'),
        ),
        migrations.AddField(
            model_name='collectfeedback',
            name='manager',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='담당자'),
        ),
    ]
