# Generated by Django 5.2.7 on 2026-05-07 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0021_collectfeedback_date_input_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer_type', models.CharField(choices=[('life', '생명보험'), ('nonlife', '손해보험')], max_length=10, verbose_name='손생구분')),
                ('category', models.CharField(choices=[('conv', '환산율/수정률'), ('pay', '지급률')], max_length=10, verbose_name='구분')),
                ('insurer', models.CharField(max_length=30, verbose_name='보험사')),
                ('file', models.FileField(upload_to='commission/rate_examples/%Y/%m/', verbose_name='첨부파일')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='원본파일명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_examples_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'verbose_name': '예시표',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['insurer_type', 'category', 'insurer'], name='commission__insurer_796b1a_idx')],
            },
        ),
    ]
