# Generated by Django 5.2.7 on 2026-05-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("commission", "0022_add_rate_example"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateExampleConversionRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),

                # 원본 파일 추적
                ("source_sheet", models.CharField(blank=True, default="", max_length=100, verbose_name="원본시트")),
                ("source_row_no", models.PositiveIntegerField(default=0, verbose_name="원본행번호")),

                # 정규화 컬럼
                ("insurer_type", models.CharField(db_index=True, max_length=10, verbose_name="손생구분")),
                ("category", models.CharField(db_index=True, max_length=10, verbose_name="구분")),
                ("insurer", models.CharField(db_index=True, max_length=30, verbose_name="보험사")),
                ("coverage_type", models.CharField(blank=True, default="", max_length=50, verbose_name="보종")),
                ("strategy_flag", models.CharField(blank=True, default="", max_length=30, verbose_name="전략유무")),
                ("product_name", models.CharField(blank=True, default="", max_length=255, verbose_name="상품명")),
                ("plan_type", models.CharField(blank=True, default="", max_length=100, verbose_name="구분")),
                ("pay_period", models.CharField(blank=True, default="", max_length=50, verbose_name="납기")),
                ("year1", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name="1차년")),
                ("year2", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name="2차년")),
                ("year3", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name="3차년")),
                ("year4", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name="4차년")),
                ("created_at", models.DateTimeField(auto_now_add=True)),

                ("source_file", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="conversion_rows",
                    to="commission.rateexample",
                    verbose_name="원본 예시표 파일",
                )),
            ],
            options={
                "verbose_name": "예시표 환산율/수정률 정규화 행",
                "verbose_name_plural": "예시표 환산율/수정률 정규화 행",
                "ordering": ["insurer_type", "insurer", "coverage_type", "product_name", "pay_period", "id"],
                "indexes": [
                    models.Index(fields=["insurer_type", "category", "insurer"], name="idx_re_conv_scope"),
                    models.Index(fields=["source_file", "source_sheet"], name="idx_re_conv_source"),
                ],
            },
        ),
    ]