# Generated by Django 5.2.7 on 2026-05-11 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0023_rate_example_conversion_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateExamplePayRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_sheet', models.CharField(blank=True, default='', max_length=100, verbose_name='원본시트')),
                ('source_row_no', models.PositiveIntegerField(default=0, verbose_name='원본행번호')),
                ('insurer_type', models.CharField(db_index=True, max_length=10, verbose_name='손생구분')),
                ('category', models.CharField(db_index=True, default='pay', max_length=10, verbose_name='구분')),
                ('insurer', models.CharField(db_index=True, max_length=30, verbose_name='보험사')),
                ('tier', models.CharField(blank=True, default='5천만↑', max_length=20, verbose_name='지급구간')),
                ('coverage_type', models.CharField(blank=True, default='', max_length=50, verbose_name='상품군')),
                ('col_a', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='초회')),
                ('col_b', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='1차년')),
                ('col_c', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='13회')),
                ('col_d', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='2차년구간')),
                ('col_e', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='3차년구간')),
                ('col_f', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='4차년구간')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_rows', to='commission.rateexample', verbose_name='원본 예시표 파일')),
            ],
            options={
                'verbose_name': '예시표 지급률 정규화 행',
                'verbose_name_plural': '예시표 지급률 정규화 행',
                'ordering': ['insurer_type', 'insurer', 'tier', 'source_row_no'],
                'indexes': [models.Index(fields=['insurer_type', 'category', 'insurer'], name='idx_re_pay_scope'), models.Index(fields=['source_file'], name='idx_re_pay_source')],
            },
        ),
    ]
