# Generated by Django 5.2.7 on 2026-05-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0025_fix_rateexamplepayrow_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateexample',
            name='insurer_type',
            field=models.CharField(choices=[('life', '생명보험'), ('fire', '손해보험')], max_length=10, verbose_name='손생구분'),
        ),
    ]
