# Generated by Django 5.2.7 on 2026-03-06 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Phase 4 (Account Lockout)

    CustomUser에 로그인 실패 누적/잠금 상태/관리자 해제 메타 필드를 추가합니다.

    추가 필드:
    - is_locked
    - last_login_fail_at
    - lock_cleared_at
    - lock_cleared_by
    - lock_reason
    - locked_at
    - login_fail_count
    - password_reset_by_admin_at
    """

    dependencies = [
        ("accounts", "0016_customuser_must_change_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_login_fail_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="lock_cleared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="lock_cleared_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="lock_reason",
            field=models.CharField(
                max_length=50,
                blank=True,
                default="",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="login_fail_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="password_reset_by_admin_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]