# Generated by Django 5.2.7 on 2026-04-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_is_locked_customuser_last_login_fail_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('head', 'Head'), ('leader', 'Leader'), ('basic', 'Basic'), ('resign', 'Resign'), ('inactive', 'Inactive')], default='basic', max_length=20),
        ),
    ]
