# Generated by Django 5.2.7 on 2026-04-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_customuser_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ci_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pass_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pass_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pass_verified_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
