# Generated by Django 5.2.7 on 2026-02-27 01:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('ip', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('object_type', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('object_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_audit_log',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['action', '-ts'], name='audit_audit_action_43b0ba_idx'), models.Index(fields=['user', '-ts'], name='audit_audit_user_id_366bda_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__26da80_idx'), models.Index(fields=['success', '-ts'], name='audit_audit_success_515944_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_authenticated', models.BooleanField(db_index=True, default=False)),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('path', models.CharField(db_index=True, max_length=512)),
                ('querystring', models.CharField(blank=True, default='', max_length=1024)),
                ('status_code', models.IntegerField(db_index=True)),
                ('duration_ms', models.IntegerField(db_index=True, default=0)),
                ('ip', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('referer', models.CharField(blank=True, default='', max_length=512)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_request_log',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['-ts'], name='audit_reque_ts_b49e28_idx'), models.Index(fields=['user', '-ts'], name='audit_reque_user_id_c317a6_idx'), models.Index(fields=['status_code', '-ts'], name='audit_reque_status__8dd3ee_idx'), models.Index(fields=['path', '-ts'], name='audit_reque_path_d6e51f_idx')],
            },
        ),
    ]
