# Generated by Django 5.2.7 on 2026-05-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateExampleAuditLog',
            fields=[
            ],
            options={
                'verbose_name': '예시표 감사로그',
                'verbose_name_plural': '예시표 감사로그',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('audit.auditlog',),
        ),
    ]
