# Generated by Django 5.2.7 on 2026-02-07 09:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_alter_salesrecord_insured'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDailyAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(db_index=True, max_length=7)),
                ('day', models.PositiveSmallIntegerField(db_index=True)),
                ('scope_type', models.CharField(choices=[('all', 'all'), ('part', 'part'), ('branch', 'branch')], db_index=True, max_length=10)),
                ('scope_key', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(choices=[('long', '손생장기'), ('car', '자동차'), ('long_nonlife', '손보장기'), ('long_life', '생보장기')], db_index=True, max_length=20)),
                ('amount', models.BigIntegerField(default=0)),
                ('cumsum', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dash_sales_daily_agg',
                'indexes': [models.Index(fields=['ym', 'scope_type', 'scope_key', 'category'], name='dash_sales__ym_e1e8c4_idx')],
                'unique_together': {('ym', 'day', 'scope_type', 'scope_key', 'category')},
            },
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(db_index=True, max_length=7)),
                ('asof_day', models.PositiveSmallIntegerField(db_index=True)),
                ('scope_type', models.CharField(db_index=True, max_length=10)),
                ('scope_key', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(db_index=True, max_length=20)),
                ('model_ver', models.CharField(db_index=True, default='lgbm_v1', max_length=40)),
                ('pred_total_p10', models.BigIntegerField(blank=True, null=True)),
                ('pred_total_p50', models.BigIntegerField(blank=True, null=True)),
                ('pred_total_p90', models.BigIntegerField(blank=True, null=True)),
                ('actual_to_date', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'dash_sales_forecast',
                'indexes': [models.Index(fields=['ym', 'scope_type', 'scope_key', 'asof_day'], name='dash_sales__ym_69496f_idx')],
                'unique_together': {('ym', 'asof_day', 'scope_type', 'scope_key', 'category', 'model_ver')},
            },
        ),
        migrations.CreateModel(
            name='SalesForecastDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('pred_amount_p10', models.BigIntegerField(blank=True, null=True)),
                ('pred_amount_p50', models.BigIntegerField(blank=True, null=True)),
                ('pred_amount_p90', models.BigIntegerField(blank=True, null=True)),
                ('pred_cumsum_p10', models.BigIntegerField(blank=True, null=True)),
                ('pred_cumsum_p50', models.BigIntegerField(blank=True, null=True)),
                ('pred_cumsum_p90', models.BigIntegerField(blank=True, null=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='dash.salesforecast')),
            ],
            options={
                'db_table': 'dash_sales_forecast_daily',
                'indexes': [models.Index(fields=['forecast', 'day'], name='dash_sales__forecas_2eb48f_idx')],
                'unique_together': {('forecast', 'day')},
            },
        ),
    ]
