# Generated by Django 5.2.7 on 2026-04-17 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_salesdailyagg_salesforecast_salesforecastdaily'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(db_index=True, max_length=7)),
                ('life_nl', models.CharField(db_index=True, max_length=10)),
                ('round_no', models.PositiveSmallIntegerField(db_index=True)),
                ('scope_type', models.CharField(choices=[('all', 'all'), ('part', 'part'), ('branch', 'branch')], db_index=True, max_length=10)),
                ('scope_key', models.CharField(db_index=True, max_length=100)),
                ('insurer', models.CharField(blank=True, default='', max_length=60)),
                ('total_amount', models.BigIntegerField(default=0, verbose_name='모집합계')),
                ('paid_amount', models.BigIntegerField(default=0, verbose_name='유지합계')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='대상건수')),
                ('paid_count', models.PositiveIntegerField(default=0, verbose_name='유지건수')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='유지율(%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '유지율집계',
                'verbose_name_plural': '유지율집계',
                'db_table': 'dash_retention_agg',
                'indexes': [models.Index(fields=['ym', 'scope_type', 'scope_key', 'round_no'], name='dash_retent_ym_72f02d_idx'), models.Index(fields=['ym', 'life_nl', 'scope_type', 'scope_key'], name='dash_retent_ym_276a06_idx')],
                'constraints': [models.UniqueConstraint(fields=('ym', 'life_nl', 'round_no', 'scope_type', 'scope_key', 'insurer'), name='unique_retention_agg')],
            },
        ),
        migrations.CreateModel(
            name='RetentionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.CharField(db_index=True, max_length=80, verbose_name='증권번호')),
                ('round_no', models.PositiveSmallIntegerField(db_index=True, verbose_name='대상회차')),
                ('insurer', models.CharField(db_index=True, max_length=60, verbose_name='보험사')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='상품명')),
                ('life_nl', models.CharField(choices=[('생보', '생보'), ('손보', '손보')], db_index=True, max_length=10, verbose_name='손생구분')),
                ('recruit_amount', models.BigIntegerField(verbose_name='최초(모집)인정실적')),
                ('status', models.CharField(choices=[('정상', '정상'), ('유예', '유예'), ('해지', '해지'), ('실효', '실효')], db_index=True, max_length=20, verbose_name='상태')),
                ('ym', models.CharField(db_index=True, max_length=7, verbose_name='월도(YYYY-MM)')),
                ('emp_id_snapshot', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='사원번호(스냅샷)')),
                ('name_snapshot', models.CharField(blank=True, max_length=100, null=True, verbose_name='성명(스냅샷)')),
                ('part_snapshot', models.CharField(blank=True, max_length=60, null=True, verbose_name='소속(스냅샷)')),
                ('branch_snapshot', models.CharField(blank=True, max_length=100, null=True, verbose_name='파트너(스냅샷)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_records', to=settings.AUTH_USER_MODEL, verbose_name='설계사')),
            ],
            options={
                'verbose_name': '유지율레코드',
                'verbose_name_plural': '유지율레코드',
                'db_table': 'dash_retention_record',
                'indexes': [models.Index(fields=['ym', 'round_no'], name='dash_retent_ym_a2af70_idx'), models.Index(fields=['ym', 'life_nl', 'round_no'], name='dash_retent_ym_6020cd_idx'), models.Index(fields=['ym', 'insurer', 'round_no'], name='dash_retent_ym_18fe3d_idx'), models.Index(fields=['ym', 'emp_id_snapshot'], name='dash_retent_ym_29228c_idx'), models.Index(fields=['ym', 'round_no', 'status'], name='dash_retent_ym_fc16db_idx')],
                'constraints': [models.UniqueConstraint(fields=('policy_no', 'round_no'), name='unique_retention_policy_round')],
            },
        ),
        migrations.CreateModel(
            name='RetentionUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(max_length=7, verbose_name='월도')),
                ('life_nl', models.CharField(choices=[('생보', '생보'), ('손보', '손보')], max_length=10, verbose_name='손생')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='파일명')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='행수')),
                ('upserted', models.PositiveIntegerField(default=0, verbose_name='upsert')),
                ('skipped', models.PositiveIntegerField(default=0, verbose_name='스킵')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_upload_logs', to=settings.AUTH_USER_MODEL, verbose_name='업로드계정')),
            ],
            options={
                'verbose_name': '유지율업로드이력',
                'verbose_name_plural': '유지율업로드이력',
                'db_table': 'dash_retention_upload_log',
                'constraints': [models.UniqueConstraint(fields=('ym', 'life_nl'), name='unique_retention_upload_log_ym_life_nl')],
            },
        ),
    ]
