# Generated by Django 5.2.7 on 2026-04-08 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollateralEval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('apt', '아파트'), ('villa', '빌라/다세대/연립'), ('officetel', '주거용 오피스텔'), ('house', '단독주택'), ('land', '토지(지목:대)'), ('etc', '기타(계산불가)')], max_length=20, verbose_name='물건 유형')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='주소')),
                ('kb_price', models.BigIntegerField(verbose_name='KB시세(원)')),
                ('prior_debt', models.BigIntegerField(default=0, verbose_name='기설정 채권최고액(원)')),
                ('apply_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='적용비율(%)')),
                ('max_collateral', models.BigIntegerField(verbose_name='담보설정 가능금액(원)')),
                ('source', models.CharField(choices=[('manual', '수동 입력'), ('api', 'API 자동조회')], default='manual', max_length=10, verbose_name='입력방식')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collateral_evals', to=settings.AUTH_USER_MODEL, verbose_name='조회자(플래너)')),
            ],
            options={
                'verbose_name': '담보평가',
                'verbose_name_plural': '담보평가 이력',
                'ordering': ['-created_at'],
            },
        ),
    ]
