# Generated by Django 5.2.7 on 2026-04-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_add_collateral_target_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateraleval',
            name='lease_deposit',
            field=models.BigIntegerField(default=0, verbose_name='임차보증금(원)'),
        ),
    ]
