# Generated by Django 5.2.7 on 2026-04-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_add_collateral_lease_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateraleval',
            name='property_type',
            field=models.CharField(choices=[('apt', '아파트'), ('villa_new', '빌라/다세대/오피스텔 (연식 20년 미만)'), ('villa_old', '빌라/다세대/오피스텔 (연식 20년 이상)'), ('house', '주택/단독주택'), ('land', '토지(대)'), ('etc', '기타(계산불가)')], max_length=20, verbose_name='물건 유형'),
        ),
    ]
