# Generated by Django 5.2.7 on 2026-04-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_add_collateral_lease_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateraleval',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='소유자 성명'),
        ),
        migrations.AddField(
            model_name='collateraleval',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='소유자 연락처'),
        ),
        migrations.AddField(
            model_name='collateraleval',
            name='owner_rel',
            field=models.CharField(blank=True, choices=[('self', '본인(FA)'), ('spouse', '배우자'), ('lineal', '직계존비속'), ('sibling', '형제자매'), ('third', '기타 제3자 (근저당 설정 불가)')], default='self', max_length=10, verbose_name='소유자 관계'),
        ),
    ]
