# Generated by Django 5.2.7 on 2026-04-14 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_add_collateral_owner_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_portal', models.CharField(choices=[('naver', 'Naver'), ('daum', 'Daum'), ('direct', 'Direct')], default='direct', max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('original_url', models.URLField(blank=True, max_length=1000)),
                ('portal_url', models.URLField(blank=True, max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('keyword_query', models.CharField(blank=True, max_length=120)),
                ('topic', models.CharField(blank=True, choices=[('실손보험', '실손보험'), ('자동차보험', '자동차보험'), ('생명보험', '생명보험'), ('손해보험', '손해보험'), ('GA', 'GA'), ('보험규제', '보험규제'), ('소비자 이슈', '소비자 이슈'), ('업계동향', '업계동향')], max_length=50)),
                ('tags_json', models.JSONField(blank=True, default=list)),
                ('normalized_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('raw_payload_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'board_industry_article',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['-published_at'], name='board_ind_pub_idx'), models.Index(fields=['topic'], name='board_ind_topic_idx'), models.Index(fields=['source_name'], name='board_ind_source_idx'), models.Index(fields=['is_active', 'is_hidden'], name='board_ind_vis_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndustryCollectJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('query', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ready', '준비'), ('success', '성공'), ('fail', '실패')], default='ready', max_length=20)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('inserted_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('meta_json', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_collect_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'board_industry_collect_job_log',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IndustryRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('reason_code', models.CharField(blank=True, max_length=50)),
                ('reason_text', models.CharField(blank=True, max_length=255)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('batch_key', models.CharField(blank=True, max_length=50)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='board.industryarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'board_industry_recommendation',
                'indexes': [models.Index(fields=['user', '-created_at'], name='board_ind_rec_user_idx'), models.Index(fields=['model_version'], name='board_ind_rec_model_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndustryUserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dwell_seconds', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='board.industryarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'board_industry_user_preference',
                'indexes': [models.Index(fields=['user', 'updated_at'], name='board_ind_pref_user_idx'), models.Index(fields=['article'], name='board_ind_pref_article_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'article'), name='uq_board_industry_user_article')],
            },
        ),
    ]
