# Generated by Django 5.2.7 on 2026-04-30 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_industryarticle_industrycollectjoblog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('code', models.CharField(choices=[('commission', '수수료 업무'), ('bond', '채권·환수'), ('risk', '리스크관리'), ('biz_dev', '제휴영업'), ('misc', '기타')], max_length=30, primary_key=True, serialize=False, verbose_name='분류 코드')),
                ('label', models.CharField(max_length=50, verbose_name='표시명')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
            ],
            options={
                'verbose_name': '업무 분류',
                'verbose_name_plural': '업무 분류',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='업무명')),
                ('description', models.TextField(blank=True, default='', verbose_name='메모')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='마감일')),
                ('recurrence_type', models.CharField(choices=[('none', '반복 없음'), ('monthly_open', '매달 월초 (1~10일)'), ('monthly_mid', '매달 중순'), ('monthly_end', '매달 말'), ('daily', '매일'), ('custom', '직접 지정')], default='none', max_length=20, verbose_name='반복 유형')),
                ('recurrence_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='반복 일자(custom)')),
                ('target_ym', models.CharField(blank=True, default='', max_length=7, verbose_name='귀속 월')),
                ('status', models.CharField(choices=[('pending', '대기'), ('in_progress', '진행중'), ('done', '완료'), ('skipped', '건너뜀')], default='pending', max_length=20, verbose_name='상태')),
                ('priority', models.PositiveSmallIntegerField(default=50, verbose_name='우선순위')),
                ('notify_days_before', models.PositiveSmallIntegerField(default=3, verbose_name='알림 D-N일 전')),
                ('is_notified', models.BooleanField(default=False, verbose_name='알림 발송 완료')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worktasks', to='board.workcategory', verbose_name='업무 분류')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worktasks', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
                ('related_users', models.ManyToManyField(blank=True, related_name='related_worktasks', to=settings.AUTH_USER_MODEL, verbose_name='관련 인물')),
                ('template_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='board.worktask', verbose_name='반복 원본')),
            ],
            options={
                'verbose_name': '업무 항목',
                'verbose_name_plural': '업무 항목',
                'ordering': ['priority', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkTaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='worktask_attachments/%Y/%m/', verbose_name='파일')),
                ('original_name', models.CharField(help_text='RFC5987 Content-Disposition 헤더에 사용', max_length=255, verbose_name='원본 파일명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='board.worktask', verbose_name='업무 항목')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'verbose_name': '업무 첨부파일',
                'verbose_name_plural': '업무 첨부파일',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='worktask',
            index=models.Index(fields=['owner', 'status', 'due_date'], name='wt_owner_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='worktask',
            index=models.Index(fields=['template_task', 'target_ym'], name='wt_template_ym_idx'),
        ),
    ]
