# Generated by Django 5.2.7 on 2026-04-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_workcategory_worktask_worktaskattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktask',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='workcategory',
            name='code',
            field=models.CharField(choices=[('commission', '수수료 업무'), ('bond', '채권·환수'), ('risk', '리스크관리'), ('biz_dev', '제휴영업'), ('misc', '기타'), ('fee_bond', '수수료/채권'), ('risk_retention', '리스크/유지율'), ('solicitation', '위해촉'), ('it_system', '전산'), ('meeting', '회의/미팅'), ('lease', '임대차'), ('sales_recruit', '영업/리쿠르팅')], max_length=30, primary_key=True, serialize=False, verbose_name='분류 코드'),
        ),
    ]
