# board/migrations/0025_priority_to_choices.py
# Generated by Django 5.2.7 on 2026-04-30 14:10
# ⚠️ 수동 수정: RunPython 데이터 변환 추가
#
# 변환 규칙:
#   기존 숫자값(PositiveSmallIntegerField) → CharField choices
#   val <= 33  → "high"
#   val <= 66  → "mid"  (기존 default=50 포함)
#   val >= 67  → "low"
#   변환 불가  → "mid" (안전 fallback)

from django.db import migrations, models


def priority_int_to_choices(apps, schema_editor):
    """
    기존 숫자 priority → 상/중/하 choices 값으로 변환.
    migrate 시 1회 실행. 역방향(reverse)은 noop.
    """
    WorkTask = apps.get_model("board", "WorkTask")
    bulk = []
    for task in WorkTask.objects.all():
        raw = task.priority
        try:
            val = int(raw)
            if val <= 33:
                task.priority = "high"
            elif val <= 66:
                task.priority = "mid"
            else:
                task.priority = "low"
        except (ValueError, TypeError):
            # 이미 문자열이거나 변환 불가 → 유효한 값이면 유지, 아니면 mid
            if raw not in ("high", "mid", "low"):
                task.priority = "mid"
        bulk.append(task)

    # bulk_update로 한 번에 처리 (row-by-row save 금지)
    if bulk:
        WorkTask.objects.bulk_update(bulk, ["priority"])


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_add_worktask_start_date'),
    ]

    operations = [
        # 1단계: 컬럼 타입 변경 (PositiveSmallIntegerField → CharField)
        #        choices 없이 먼저 변경해야 기존 숫자 데이터 보존됨
        migrations.AlterField(
            model_name='worktask',
            name='priority',
            field=models.CharField(
                default='mid',
                max_length=10,
                verbose_name='우선순위',
            ),
        ),
        # 2단계: 기존 숫자 데이터 → choices 값으로 변환
        migrations.RunPython(
            priority_int_to_choices,
            reverse_code=migrations.RunPython.noop,
        ),
        # 3단계: choices 제약 적용
        migrations.AlterField(
            model_name='worktask',
            name='priority',
            field=models.CharField(
                choices=[('high', '상'), ('mid', '중'), ('low', '하')],
                default='mid',
                max_length=10,
                verbose_name='우선순위',
            ),
        ),
    ]