# Generated by Django 5.2.7 on 2026-05-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_worktask_family_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktask',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('in_progress', '진행중'), ('done', '완료'), ('skipped', '보류')], default='pending', max_length=20, verbose_name='상태'),
        ),
    ]
