# django_ma/board/migrations/0029_worktask_calendar_span_mode.py

# Generated by Django 5.2.7 on 2026-05-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_worktaskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktask',
            name='calendar_span_mode',
            field=models.BooleanField(default=False, help_text='체크 시 시작일부터 마감일까지 캘린더에 기간 막대로 표시합니다.', verbose_name='캘린더 기간 막대 표시'),
        ),
    ]
