# Generated by Django 5.2.7 on 2026-04-27 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0020_alter_efficiencychange_confirm_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='efficiencychange',
            name='end_ym',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='종료월도'),
        ),
        migrations.AddField(
            model_name='efficiencychange',
            name='start_ym',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='시작월도'),
        ),
        migrations.CreateModel(
            name='EfficiencySignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(max_length=7, verbose_name='월도')),
                ('branch', models.CharField(default='-', max_length=50, verbose_name='지점')),
                ('doc_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='PDF SHA-256')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='esign/completed/', verbose_name='완성 PDF')),
                ('status', models.CharField(choices=[('pending', '서명 대기'), ('partial', '일부 서명'), ('completed', '서명 완료'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='서명 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirm_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_request', to='partner.efficiencyconfirmgroup')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esign_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '전자서명 요청',
                'verbose_name_plural': '전자서명 요청 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EfficiencyConfirmSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('deduct', '공제대상자'), ('pay', '지급대상자'), ('head_confirm', '최고관리자 확인')], max_length=20, verbose_name='역할')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='서명일시')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='서명 IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('session_key', models.CharField(blank=True, default='', max_length=40, verbose_name='세션 키 스냅샷')),
                ('pass_verified_at_sign', models.DateTimeField(blank=True, null=True, verbose_name='PASS 인증일시 스냅샷')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esign_participations', to=settings.AUTH_USER_MODEL, verbose_name='서명자')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signs', to='partner.efficiencysignrequest', verbose_name='서명 요청')),
            ],
            options={
                'verbose_name': '서명 참여자',
                'verbose_name_plural': '서명 참여자 목록',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='efficiencysignrequest',
            index=models.Index(fields=['ym', 'branch'], name='partner_eff_ym_f35d25_idx'),
        ),
        migrations.AddIndex(
            model_name='efficiencysignrequest',
            index=models.Index(fields=['status'], name='partner_eff_status_31f628_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='efficiencyconfirmsign',
            unique_together={('request', 'signer')},
        ),
    ]
